version: '3.6'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password1
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
